version: "3.9"
services:
  server_api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "3001:3001"
    container_name: server_api
    restart: always